
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="cogged_up"
version="${mod_version}"
displayName="Create: Cogged Up"
authors="LampBoy"
logoFile="icon.png"
description='''
A mod that adds bunch of new cogwheels based on materials of Create
'''

[[mixins]]
config="cogged_up.mixins.json"

[[dependencies.cogged_up]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cogged_up]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cogged_up]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21)"
    ordering="NONE"
    side="BOTH"
